[tool.poetry]
name = "backend"
version = "0.1.0"
description = "This is a fullstack application using react-ts as frontend,vite+FastAPI as backend,and postgresql as Database"
authors = ["FayeValentina <shawshankei@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11"
fastapi = ">=0.115.6,<0.116.0"
uvicorn = ">=0.34.0,<0.35.0"
sqlalchemy = "^2.0.0"
psycopg2-binary = "^2.9.0"
alembic = "^1.12.0"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}  # JWT tokens
passlib = {extras = ["bcrypt"], version = "^1.7.4"}           # 密码哈希
pydantic = {extras = ["email"], version = "^2.0.0"}           # 数据验证
python-multipart = "^0.0.9"                                   # 文件上传
python-dotenv = "^1.0.0"                                      # 环境变量管理
emails = "^0.6"                                              # 邮件支持（可选）

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
black = "^23.0.0"
flake8 = "^6.0.0"
mypy = "^1.0.0"
pytest-cov = "^4.1.0"                                        # 测试覆盖率
httpx = "^0.24.0"                                           # 异步HTTP客户端，用于测试

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = ["error"]
addopts = "--strict-markers --strict-config -ra"

[tool.black]
line-length = 88
target-version = ["py311"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3