"""change_task_type_to_string

Revision ID: 789b505bf7a8
Revises: 94d2146c0d5a
Create Date: 2025-08-19 19:14:46.896182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '789b505bf7a8'
down_revision: Union[str, None] = '94d2146c0d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Change task_type from ENUM to VARCHAR(50)
    op.execute("ALTER TABLE task_configs ALTER COLUMN task_type TYPE VARCHAR(50)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: This downgrade recreates the ENUM type, but data might be lost if new task types were added
    op.execute("""
        CREATE TYPE tasktype AS ENUM (
            'bot_scraping', 'manual_scraping', 'batch_scraping',
            'cleanup_tokens', 'cleanup_content', 
            'send_email', 'send_notification',
            'data_export', 'data_backup', 'data_analysis',
            'health_check', 'system_monitor', 'log_rotation', 'timeout_monitor', 'cleanup_timeout_tasks',
            'test_timeout', 'test_failure', 'test_short_timeout'
        )
    """)
    op.execute("ALTER TABLE task_configs ALTER COLUMN task_type TYPE tasktype USING task_type::tasktype")
    # ### end Alembic commands ###
