"""delete token and schedule

Revision ID: bda0acbea51f
Revises: 55ad71a1a352
Create Date: 2025-08-18 14:55:20.040881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda0acbea51f'
down_revision: Union[str, None] = '55ad71a1a352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'tasktype', ['BATCH_SCRAPING', 'BOT_SCRAPING', 'CLEANUP_CONTENT', 'CLEANUP_EVENTS', 'CLEANUP_TIMEOUT_TASKS', 'CLEANUP_TOKENS', 'DATA_ANALYSIS', 'DATA_BACKUP', 'DATA_EXPORT', 'HEALTH_CHECK', 'LOG_ROTATION', 'MANUAL_SCRAPING', 'SEND_EMAIL', 'SEND_NOTIFICATION', 'SYSTEM_MONITOR', 'TIMEOUT_MONITOR'], ['BATCH_SCRAPING', 'BOT_SCRAPING', 'CLEANUP_CONTENT', 'CLEANUP_TIMEOUT_TASKS', 'CLEANUP_TOKENS', 'DATA_ANALYSIS', 'DATA_BACKUP', 'DATA_EXPORT', 'HEALTH_CHECK', 'LOG_ROTATION', 'MANUAL_SCRAPING', 'SEND_EMAIL', 'SEND_NOTIFICATION', 'SYSTEM_MONITOR', 'TIMEOUT_MONITOR'], [('task_configs', 'task_type')], False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'tasktype', ['BATCH_SCRAPING', 'BOT_SCRAPING', 'CLEANUP_CONTENT', 'CLEANUP_TIMEOUT_TASKS', 'CLEANUP_TOKENS', 'DATA_ANALYSIS', 'DATA_BACKUP', 'DATA_EXPORT', 'HEALTH_CHECK', 'LOG_ROTATION', 'MANUAL_SCRAPING', 'SEND_EMAIL', 'SEND_NOTIFICATION', 'SYSTEM_MONITOR', 'TIMEOUT_MONITOR'], ['BATCH_SCRAPING', 'BOT_SCRAPING', 'CLEANUP_CONTENT', 'CLEANUP_EVENTS', 'CLEANUP_TIMEOUT_TASKS', 'CLEANUP_TOKENS', 'DATA_ANALYSIS', 'DATA_BACKUP', 'DATA_EXPORT', 'HEALTH_CHECK', 'LOG_ROTATION', 'MANUAL_SCRAPING', 'SEND_EMAIL', 'SEND_NOTIFICATION', 'SYSTEM_MONITOR', 'TIMEOUT_MONITOR'], [('task_configs', 'task_type')], True)
    # ### end Alembic commands ###
